version: '3.1'

networks:
  rcn:
    external:
      name: rcn
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    container_name: db-node
    command: -p 5435
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5435:5435
    networks:
      - rcn
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    restart: always
    build:
      context: api
      dockerfile: docker/Dockerfile
    image: api-makito
    container_name: api-makito
    volumes:
      - ./api/src/:/project/
    ports:
      - 8080:8080
    links:
      - db:postgres
    depends_on: 
      - db
    env_file:
      - .env
    networks:
      - rcn

volumes:
  db-data:
    driver: local