version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: db-node
    command: -p 5435
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5435:5435
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    restart: always
    build:
      dockerfile: api/docker/Dockerfile
    image: api-makito
    container_name: api-makito
    volumes:
      - ./api/src/:/project/
    ports:
      - 8080:8080
    links:
      - db:postgres
    depends_on: 
      - db
    env_file:
      - .env

volumes:
  db-data:
    driver: local